use crate::domain::error::Result;
use anyhow::Context;
use rcgen::{Certificate, CertificateParams};
use std::path::PathBuf;
use time::{Duration, OffsetDateTime};
use tracing::{debug, info};

/// Represents a Certificate Authority
pub struct CertificateAuthority {
    certificate: Certificate,
    pem_cert: String,
    pem_key: String,
}

impl CertificateAuthority {
    /// Creates or loads a CA certificate
    pub fn new_or_load(cert_path: &PathBuf, key_path: &PathBuf) -> Result<Self> {
        if cert_path.exists() && key_path.exists() {
            debug!("Loading CA certificate from disk");
            Self::load(cert_path, key_path)
        } else {
            debug!("Generating new CA certificate");
            Self::generate()
        }
    }

    /// Generates a new CA certificate
    pub fn generate() -> Result<Self> {
        let subject_alt_names = vec!["pupoxide-ca".to_string()];
        let mut params = CertificateParams::new(subject_alt_names);
        params.distinguished_name = rcgen::DistinguishedName::new();
        params
            .distinguished_name
            .push(rcgen::DnType::CommonName, "pupoxide-ca");
        params.is_ca = rcgen::IsCa::Ca(rcgen::BasicConstraints::Unconstrained);
        let certificate =
            Certificate::from_params(params).context("Failed to generate CA certificate")?;

        let pem_cert = certificate
            .serialize_pem()
            .context("Failed to serialize CA certificate")?;
        let pem_key = certificate.serialize_private_key_pem();

        info!("Generated new CA certificate");
        Ok(Self {
            certificate,
            pem_cert,
            pem_key,
        })
    }

    /// Loads CA from PEM files (simplified - requires the cert was generated by rcgen)
    pub fn load(cert_path: &PathBuf, key_path: &PathBuf) -> Result<Self> {
        let pem_cert =
            std::fs::read_to_string(cert_path).context("Failed to read CA certificate")?;

        let pem_key = std::fs::read_to_string(key_path).context("Failed to read CA private key")?;

        let key_pair =
            rcgen::KeyPair::from_pem(&pem_key).context("Failed to parse CA private key")?;

        // Reconstruct the certificate object from the private key
        let subject_alt_names = vec!["pupoxide-ca".to_string()];
        let mut params = CertificateParams::new(subject_alt_names);
        params.distinguished_name = rcgen::DistinguishedName::new();
        params
            .distinguished_name
            .push(rcgen::DnType::CommonName, "pupoxide-ca");
        params.is_ca = rcgen::IsCa::Ca(rcgen::BasicConstraints::Unconstrained);
        params.key_pair = Some(key_pair);
        let certificate = Certificate::from_params(params)
            .context("Failed to regenerate CA certificate from key")?;

        Ok(Self {
            certificate,
            pem_cert,
            pem_key,
        })
    }

    /// Saves CA to disk
    pub fn save(&self, cert_path: &PathBuf, key_path: &PathBuf) -> Result<()> {
        std::fs::write(cert_path, &self.pem_cert).context("Failed to write CA certificate")?;
        std::fs::write(key_path, &self.pem_key).context("Failed to write CA private key")?;

        info!("Saved CA certificate to {:?}", cert_path);
        Ok(())
    }

    /// Returns PEM-encoded certificate
    pub fn cert_pem(&self) -> &str {
        &self.pem_cert
    }

    /// Returns PEM-encoded private key
    pub fn key_pem(&self) -> &str {
        &self.pem_key
    }

    /// Signs a certificate signing request (CSR)
    /// Returns the signed certificate in PEM format
    pub fn sign_csr(&self, node_id: &str, days_valid: u32) -> Result<String> {
        // Generate a new certificate for the agent, signed by this CA
        let subject_alt_names = vec![node_id.to_string()];
        let mut agent_params = CertificateParams::new(subject_alt_names);
        agent_params.is_ca = rcgen::IsCa::NoCa;
        agent_params.distinguished_name = rcgen::DistinguishedName::new();
        agent_params
            .distinguished_name
            .push(rcgen::DnType::CommonName, node_id);

        // Set validity period
        let now = OffsetDateTime::now_utc();
        agent_params.not_before = now;
        agent_params.not_after = now + Duration::days(days_valid as i64);

        // Create agent certificate
        let agent_cert =
            Certificate::from_params(agent_params).context("Failed to create agent certificate")?;

        // Serialize with CA signature (using the CA's private key)
        let signed_pem = agent_cert
            .serialize_pem_with_signer(&self.certificate)
            .context("Failed to serialize agent certificate with CA signature")?;

        debug!("Signed certificate for {}", node_id);
        Ok(signed_pem)
    }

    /// Sign a certificate that was already generated by the agent (preserves agent's public key)
    pub fn sign_csr_with_client_cert(
        &self,
        node_id: &str,
        agent_cert_pem: &str,
        days_valid: u32,
    ) -> Result<String> {
        // Note: Ideally we would extract the public key from the agent's cert and
        // create a new cert with that key. However, rcgen doesn't provide easy CSR/cert parsing.
        // As a workaround, we create a new cert and rely on the agent having the matching
        // private key from its self-generated cert.

        // For now, we create a new cert but ensure it uses the same node_id
        // so the agent can match it with its private key.
        let _ = agent_cert_pem; // Will use this when cert parsing is implemented

        // Fall back to the standard signing
        self.sign_csr(node_id, days_valid)
    }

    /// Generates a new server certificate and private key signed by this CA
    pub fn generate_server_cert(&self, hostname: &str) -> Result<(String, String)> {
        let subject_alt_names = vec![hostname.to_string()];
        let mut params = CertificateParams::new(subject_alt_names);
        params.is_ca = rcgen::IsCa::NoCa;
        params.distinguished_name = rcgen::DistinguishedName::new();
        params
            .distinguished_name
            .push(rcgen::DnType::CommonName, hostname);

        // Add serverAuth extended key usage (required for HTTPS servers)
        params
            .extended_key_usages
            .push(rcgen::ExtendedKeyUsagePurpose::ServerAuth);

        let now = OffsetDateTime::now_utc();
        params.not_before = now;
        params.not_after = now + Duration::days(365);

        let cert = Certificate::from_params(params)
            .context("Failed to generate server certificate params")?;

        let cert_pem = cert
            .serialize_pem_with_signer(&self.certificate)
            .context("Failed to serialize server certificate with CA signature")?;

        let key_pem = cert.serialize_private_key_pem();

        Ok((cert_pem, key_pem))
    }
}

/// Represents an Agent Certificate Request
pub struct AgentCertificateRequest {
    pub node_id: String,
    pub csr_pem: String,
}

impl AgentCertificateRequest {
    /// Generates a new private key and CSR for an agent
    pub fn generate(node_id: &str) -> Result<(Self, String, String)> {
        let subject_alt_names = vec![node_id.to_string()];
        let mut params = CertificateParams::new(subject_alt_names);
        params.distinguished_name = rcgen::DistinguishedName::new();
        params
            .distinguished_name
            .push(rcgen::DnType::CommonName, node_id);
        params.is_ca = rcgen::IsCa::NoCa;

        let private_key =
            Certificate::from_params(params).context("Failed to generate agent private key")?;

        let csr_pem = private_key
            .serialize_request_pem()
            .context("Failed to serialize CSR")?;
        let key_pem = private_key.serialize_private_key_pem();
        let cert_pem = private_key
            .serialize_pem()
            .context("Failed to serialize self-signed certificate")?;

        let req = AgentCertificateRequest {
            node_id: node_id.to_string(),
            csr_pem,
        };

        debug!("Generated CSR for agent {}", node_id);
        Ok((req, key_pem, cert_pem))
    }
}

/// Saves certificate and key to disk
pub fn save_agent_certificate(
    cert_pem: &str,
    key_pem: &str,
    cert_path: &PathBuf,
    key_path: &PathBuf,
) -> Result<()> {
    std::fs::write(cert_path, cert_pem).context("Failed to write agent certificate")?;
    std::fs::write(key_path, key_pem).context("Failed to write agent private key")?;

    info!("Saved agent certificate to {:?}", cert_path);
    Ok(())
}

/// Extracts the Common Name (CN) from DER-encoded X.509 certificate bytes.
pub fn extract_cn_from_der(der: &[u8]) -> Result<String> {
    use x509_cert::Certificate;
    use x509_cert::der::{Decode, asn1::ObjectIdentifier};

    // OID for Common Name (2.5.4.3)
    const CN_OID: ObjectIdentifier = ObjectIdentifier::new_unwrap("2.5.4.3");

    let cert = Certificate::from_der(der)
        .map_err(|e| anyhow::anyhow!("Failed to parse DER certificate: {}", e))?;

    for rdn in cert.tbs_certificate.subject.0.iter() {
        for ava in rdn.0.iter() {
            if ava.oid == CN_OID {
                if let Ok(s) = ava
                    .value
                    .decode_as::<x509_cert::der::asn1::PrintableStringRef<'_>>()
                {
                    return Ok(s.as_str().to_string());
                }
                if let Ok(s) = ava
                    .value
                    .decode_as::<x509_cert::der::asn1::Utf8StringRef<'_>>()
                {
                    return Ok(s.as_str().to_string());
                }
                if let Ok(s) = ava
                    .value
                    .decode_as::<x509_cert::der::asn1::Ia5StringRef<'_>>()
                {
                    return Ok(s.as_str().to_string());
                }
                anyhow::bail!("Unsupported ASN.1 string type for CN");
            }
        }
    }

    anyhow::bail!("Common Name (CN) not found in certificate")
}

/// Extracts the Common Name (CN) from PEM-encoded X.509 certificate string.
pub fn extract_cn_from_pem(pem: &str) -> Result<String> {
    let mut reader = std::io::BufReader::new(pem.as_bytes());
    let certs = rustls_pemfile::certs(&mut reader)
        .collect::<std::result::Result<Vec<_>, _>>()
        .context("Failed to parse PEM certificate")?;
    let first_cert = certs
        .first()
        .ok_or_else(|| anyhow::anyhow!("No certificate found in PEM"))?;
    extract_cn_from_der(first_cert)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ca_generation() {
        let ca = CertificateAuthority::generate().expect("Failed to generate CA");
        assert!(!ca.cert_pem().is_empty());
        assert!(!ca.key_pem().is_empty());
    }

    #[test]
    fn test_csr_generation() {
        let (csr, key_pem, cert_pem) =
            AgentCertificateRequest::generate("test-agent").expect("Failed to generate CSR");
        assert!(!csr.csr_pem.is_empty());
        assert!(!key_pem.is_empty());
        assert!(!cert_pem.is_empty());
    }

    #[test]
    fn test_sign_csr() {
        let ca = CertificateAuthority::generate().expect("Failed to generate CA");

        let signed = ca.sign_csr("test-agent", 365).expect("Failed to sign CSR");
        assert!(!signed.is_empty());
        assert!(signed.contains("BEGIN CERTIFICATE"));
    }

    #[test]
    fn test_extract_cn() {
        let ca = CertificateAuthority::generate().expect("Failed to generate CA");
        let agent_cert_pem = ca
            .sign_csr("my-agent-node", 365)
            .expect("Failed to sign agent cert");
        let cn = extract_cn_from_pem(&agent_cert_pem).expect("Failed to extract CN");
        assert_eq!(cn, "my-agent-node");
    }

    #[test]
    fn test_generate_server_cert() {
        let ca = CertificateAuthority::generate().expect("Failed to generate CA");
        let (server_cert, server_key) = ca
            .generate_server_cert("localhost")
            .expect("Failed to generate server cert");
        assert!(server_cert.contains("BEGIN CERTIFICATE"));
        assert!(server_key.contains("BEGIN PRIVATE KEY"));

        let cn = extract_cn_from_pem(&server_cert).expect("Failed to extract server CN");
        assert_eq!(cn, "localhost");
    }

    #[test]
    fn test_private_key_loading() {
        let ca = CertificateAuthority::generate().expect("Failed to generate CA");
        let (_, server_key) = ca
            .generate_server_cert("localhost")
            .expect("Failed to generate server cert");
        let mut key_reader = std::io::BufReader::new(server_key.as_bytes());
        let key_der = rustls_pemfile::private_key(&mut key_reader)
            .expect("Failed to read private key")
            .expect("No private key found");
        let private_key = tokio_rustls::rustls::PrivateKey(key_der.secret_der().to_vec());
        assert!(!private_key.0.is_empty());
    }
}
